[package]
name = "vulkan_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
raw-window-handle = "0.6.2"
winit = { version = "=0.31.0-beta.2", default-features = false }
bevy_ecs = { version = "0.18.0", default-features = false, features = [
    "std",
    "backtrace",
    "multi_threaded",
] }
vulkanite = { git = "https://github.com/Jerrody/vulkanite", features = [
    "version_1_4",
    "loaded",
    "ext_unified_image_layouts",
    "ext_descriptor_buffer",
    "raw-window-handle",
    "ext_swapchain",
    "ext_shader_object",
    "ext_debug_utils",
    "ext_mesh_shader",
    "ext_validation_features",
] }
vma = { package = "vk-mem", git = "https://github.com/Jerrody/vulkanite-mem-rs", branch = "vulkanite" }
asset-importer = { version = "0.7.0", features = ["bytemuck", "glam"] }
glam = { version = "0.31.0", features = ["fast-math", "bytemuck"] }
bytemuck = "1.24.0"
meshopt = "0.6.2"
ahash = "0.8.12"
uuid = { version = "1.19", default-features = false, features = ["v4"] }
rayon = { version = "1.11.0", default-features = false }
image = { version = "0.25.9", default-features = false, features = [
    "png",
    "jpeg",
    "hdr",
] }
ktx2-rw = "0.2.4"
nameof = "1.3.0"
dolly = "0.6.0"
fast_image_resize = { version = "6.0.0", features = ["image"] }

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
