[package]
name = "vulkan_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
raw-window-handle = "0.6.2"
winit = { version = "=0.31.0-beta.2", default-features = false }
bevy_ecs = { version = "0.17.3", default-features = false, features = [
    "std",
    "backtrace",
] }
vulkanite = { version = "0.0.11", features = [
    "version_1_3",
    "loaded",
    "ext_unified_image_layouts",
    "ext_descriptor_buffer",
    "raw-window-handle",
    "ext_swapchain",
    "ext_shader_object",
    "ext_debug_utils",
    "ext_synchronization2",
] }
vma = { package = "vk-mem", git = "https://github.com/Macdu/vk-mem-rs.git", branch = "vulkanite" }

[profile.dev]
opt-level = 1
