[workspace]
resolver = "3"
members = ["crates/engine", "crates/game_logic", "crates/game_runner"]

[workspace.dependencies]
bevy_ecs = { version = "0.18.0", default-features = false, features = [
    "std",
    "backtrace",
    "multi_threaded",
] }
glam = { version = "0.32.0", features = ["fast-math", "bytemuck"] }
engine = { path = "crates/engine" }
game_logic = { path = "crates/game_logic" }

[profile.dev]
opt-level = 2
codegen-units = 256
incremental = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
