[package]
name = "vulkan_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
raw-window-handle = "0.6.2"
winit = { version = "=0.31.0-beta.2", default-features = false }
bevy_ecs = { version = "0.17.3", default-features = false, features = [
    "std",
    "backtrace",
] }
vulkanalia = "0.34.0"
vulkanalia-bootstrap = { git = "https://github.com/Jerrody/vulkanalia-bootstrap" }
vma = { package = "vulkanalia-vma", version = "0.8.0" }

[profile.dev]
opt-level = 1
