[package]
name = "game_runner"
version = "0.1.0"
edition = "2024"
build = "../../build.rs"

[dependencies]
winit = { version = "=0.31.0-beta.2", default-features = false }
engine = { workspace = true }

[build-dependencies]
cargo_metadata = "0.23.1"
