[package]
name = "game_logic"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
engine = { workspace = true }
bevy_ecs = { workspace = true }
glam = { workspace = true }
winit = { workspace = true }
